name: Python Tests with Reports

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Run tests with JUnit + HTML + Allure
      run: |
        pytest --junitxml=report.xml
        pytest --html=report.html --self-contained-html
        pytest --alluredir=allure-results

    - name: Upload Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          report.xml
          report.html
